# Redirect to bypass CORS
/api/*  https://itxperts.co.in/blog/wp-json/:splat  200
[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  CI = "false"
